/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User1
 */
public class Display extends javax.swing.JFrame {
    DefaultTableModel model;
    DefaultListModel<String> piket;
    DefaultListModel<String> rapat;
    /**
     * Creates new form Display
     */
    public Display() {
        initComponents();
        model = (DefaultTableModel) jTable.getModel();
        this.piket = new DefaultListModel<>();
        this.jPiket.setModel(piket);
        this.rapat = new DefaultListModel<>();
        this.jRapat.setModel(rapat);
    }

    public void getSum(){
        int sum = 0;
        for (int i = 0; i < jTable.getRowCount(); i++) {
            sum = sum + 1;   
        }
        jHitung.setText("Jumlah Anggota = "+Integer.toString(sum));
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLogo2 = new javax.swing.JLabel();
        jTeks = new javax.swing.JLabel();
        jNama = new javax.swing.JLabel();
        jDivisi = new javax.swing.JLabel();
        jTahun = new javax.swing.JLabel();
        jIsiNama = new javax.swing.JTextField();
        jIsiTahun = new javax.swing.JTextField();
        jIsiDivisi = new javax.swing.JComboBox<>();
        jPJ = new javax.swing.JLabel();
        jIsiPJ = new javax.swing.JTextField();
        jButtonTambah = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonDeleteAll = new javax.swing.JButton();
        jTeks1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jNamaFile = new javax.swing.JLabel();
        jtxt = new javax.swing.JTextField();
        jButtonBacaFile = new javax.swing.JButton();
        jLogo3 = new javax.swing.JLabel();
        jButtonSimpan = new javax.swing.JButton();
        jHitung = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jIffa = new javax.swing.JLabel();
        jButtonPiket = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPiket = new javax.swing.JList<>();
        jTeks2 = new javax.swing.JLabel();
        jButtonRapat = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jRapat = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTeks5 = new javax.swing.JLabel();
        jNamaBaik = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonTentukanRapat = new javax.swing.JButton();
        jRajinPiket = new javax.swing.JLabel();
        jRajinRapat = new javax.swing.JLabel();
        jButtonTentukanPiket = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLogo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/logo2.png"))); // NOI18N
        jLogo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTeks.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTeks.setText("Form Keanggotaan");

        jNama.setText("Nama  :");

        jDivisi.setText("Divisi   :");

        jTahun.setText("Tahun :");

        jIsiDivisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kominfo", "Litbang", "Diklat", "Ekokeu" }));
        jIsiDivisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIsiDivisiActionPerformed(evt);
            }
        });

        jPJ.setText("PJ       :");

        jButtonTambah.setText("Tambah");
        jButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonDeleteAll.setText("ClearAll");
        jButtonDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteAllActionPerformed(evt);
            }
        });

        jTeks1.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTeks1.setText("Daftar Anggota");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Divisi", "PJ", "Tahun"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        jNamaFile.setText("Nama File  :");

        jtxt.setForeground(new java.awt.Color(160, 160, 160));
        jtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt.setText("dbo.txt");

        jButtonBacaFile.setText("Baca File");
        jButtonBacaFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBacaFileActionPerformed(evt);
            }
        });

        jLogo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/logo3.png"))); // NOI18N
        jLogo3.setText("jLabel1");

        jButtonSimpan.setBackground(new java.awt.Color(0, 255, 102));
        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });

        jHitung.setForeground(new java.awt.Color(255, 0, 51));
        jHitung.setText("Jumlah Anggota = 0");

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jIffa.setBackground(new java.awt.Color(153, 255, 0));
        jIffa.setForeground(new java.awt.Color(204, 0, 255));
        jIffa.setText("©IffaZN__");

        jButtonPiket.setText("Piket");
        jButtonPiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPiketActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jPiket);

        jTeks2.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTeks2.setText("KEAKTIFAN");

        jButtonRapat.setText("Rapat");
        jButtonRapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRapatActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(jRapat);

        jLabel1.setText("Menjalankan Piket");

        jLabel2.setText("Hadir Rapat");

        jTeks5.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTeks5.setText("Anggota Terbaik");

        jNamaBaik.setText("Rajin Rapat :");

        jLabel5.setText("Rajin Piket  :");

        jButtonTentukanRapat.setText("Tentukan");
        jButtonTentukanRapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTentukanRapatRapatActionPerformed(evt);
            }
        });

        jRajinPiket.setText("-");

        jRajinRapat.setText("-");

        jButtonTentukanPiket.setText("Tentukan");
        jButtonTentukanPiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTentukanPiketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jTeks2)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(33, 33, 33)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(46, 46, 46)
                                            .addComponent(jLabel2)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(64, 64, 64)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel5)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jRajinPiket))
                                                .addComponent(jTeks5)
                                                .addComponent(jButtonTentukanPiket)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jNamaBaik)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jRajinRapat))
                                                .addComponent(jButtonTentukanRapat)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jIffa))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButtonTambah)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonUpdate)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonDelete)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonDeleteAll))
                                        .addComponent(jTeks)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jNama)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jIsiNama, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jDivisi)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jIsiDivisi, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTahun)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jIsiTahun))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jPJ)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jIsiPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(31, 31, 31)
                                            .addComponent(jLogo3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton1)
                                            .addGap(47, 47, 47))))))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLogo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTeks1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jHitung)
                                        .addGap(150, 150, 150)
                                        .addComponent(jButtonPiket)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonRapat)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonSimpan))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jNamaFile)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonBacaFile)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLogo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTeks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jNama)
                            .addComponent(jIsiNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDivisi)
                            .addComponent(jIsiDivisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPJ)
                            .addComponent(jIsiPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTahun)
                            .addComponent(jIsiTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonTambah)
                            .addComponent(jButtonUpdate)
                            .addComponent(jButtonDelete)
                            .addComponent(jButtonDeleteAll))
                        .addGap(18, 18, 18)
                        .addComponent(jTeks1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLogo3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNamaFile)
                    .addComponent(jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBacaFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSimpan)
                        .addComponent(jButtonPiket)
                        .addComponent(jButtonRapat))
                    .addComponent(jHitung))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTeks2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jTeks5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jRajinPiket))
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonTentukanPiket)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNamaBaik)
                            .addComponent(jRajinRapat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonTentukanRapat)
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addComponent(jIffa, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jIsiDivisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIsiDivisiActionPerformed
        // TODO add your handling code her
    }//GEN-LAST:event_jIsiDivisiActionPerformed

    private void jButtonBacaFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBacaFileActionPerformed
        String filePath = "D:\\Informatics\\SM 4\\PBO\\Praktikum\\TuBes\\dbo.txt";
        File file = new File(filePath);
        
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim();
            String[] columnNames = firstLine.split(",");
            DefaultTableModel model = (DefaultTableModel)jTable.getModel();
            model.setColumnIdentifiers(columnNames);
            
            Object[] tableLines = br.lines().toArray();
            for (int i = 0; i < tableLines.length; i++) {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split("/");
                model.addRow(dataRow);
            }
        } catch (Exception ex) {
                 System.out.println("Gagal Baca");
        }
        
    }//GEN-LAST:event_jButtonBacaFileActionPerformed

    private void jButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahActionPerformed
        model.insertRow(model.getRowCount(), new Object[]{jIsiNama.getText(), jIsiDivisi.getSelectedItem(), jIsiPJ.getText(), jIsiTahun.getText()});
        jIsiNama.setText("");
        jIsiPJ.setText("");
        jIsiTahun.setText("");
    }//GEN-LAST:event_jButtonTambahActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        model.setValueAt(jIsiNama.getText(), jTable.getSelectedRow(), 0);
        model.setValueAt(jIsiDivisi.getSelectedItem(), jTable.getSelectedRow(), 1);
        model.setValueAt(jIsiPJ.getText(), jTable.getSelectedRow(), 2);
        model.setValueAt(jIsiTahun.getText(), jTable.getSelectedRow(), 3);
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        jIsiNama.setText(String.valueOf(model.getValueAt(jTable.getSelectedRow(), 0)));
        jIsiDivisi.setSelectedItem(String.valueOf(model.getValueAt(jTable.getSelectedRow(), 1)));
        jIsiPJ.setText(String.valueOf(model.getValueAt(jTable.getSelectedRow(), 2)));
        jIsiTahun.setText(String.valueOf(model.getValueAt(jTable.getSelectedRow(), 3)));
    }//GEN-LAST:event_jTableMouseClicked

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        model.removeRow(jTable.getSelectedRow());
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteAllActionPerformed
        ((DefaultTableModel)jTable.getModel()).setNumRows(0);
    }//GEN-LAST:event_jButtonDeleteAllActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login Info = new Login();
        Info.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
       getSum();
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jButtonPiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPiketActionPerformed
        jTable.getSelectedRow();
        piket.addElement(jIsiNama.getText());
    }//GEN-LAST:event_jButtonPiketActionPerformed

    private void jButtonRapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRapatActionPerformed
        jTable.getSelectedRow();
        rapat.addElement(jIsiNama.getText());
    }//GEN-LAST:event_jButtonRapatActionPerformed

    private void jButtonTentukanRapatRapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTentukanRapatRapatActionPerformed
        Integer maxCount;
        String  maxValue;
        maxValue = rapat.getElementAt(0);
        maxCount = 1;
        for (int i = 0; i < rapat.getSize(); ++i) {
            Integer count = 0;
                for (int j = 1; j < rapat.getSize(); ++j) {
                    if (rapat.getElementAt(j) == rapat.getElementAt(i)) ++count;
                }
            if (count > maxCount) {
                maxCount = count;
                maxValue = rapat.getElementAt(i);
            }
        }
        jRajinRapat.setText(maxValue);
    }//GEN-LAST:event_jButtonTentukanRapatRapatActionPerformed

    private void jButtonTentukanPiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTentukanPiketActionPerformed
        Integer maxcount;
        String maxvalue;
        maxvalue = piket.getElementAt(1);
        maxcount = 1;
        for (int i = 0; i < piket.getSize(); i++) {
            Integer count = 0;
                for (int j = 1; j < piket.getSize(); j++) {
                    if (piket.getElementAt(j) == piket.getElementAt(i)) count++;
                }
            if (count > maxcount) {
                maxcount = count;
                maxvalue = piket.getElementAt(i);
            }
        }
        jRajinPiket.setText(maxvalue);
    }//GEN-LAST:event_jButtonTentukanPiketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBacaFile;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonDeleteAll;
    private javax.swing.JButton jButtonPiket;
    private javax.swing.JButton jButtonRapat;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JButton jButtonTambah;
    private javax.swing.JButton jButtonTentukanPiket;
    private javax.swing.JButton jButtonTentukanRapat;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jDivisi;
    private javax.swing.JLabel jHitung;
    private javax.swing.JLabel jIffa;
    private javax.swing.JComboBox<String> jIsiDivisi;
    private javax.swing.JTextField jIsiNama;
    private javax.swing.JTextField jIsiPJ;
    private javax.swing.JTextField jIsiTahun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLogo2;
    private javax.swing.JLabel jLogo3;
    private javax.swing.JLabel jNama;
    private javax.swing.JLabel jNamaBaik;
    private javax.swing.JLabel jNamaFile;
    private javax.swing.JLabel jPJ;
    private javax.swing.JList<String> jPiket;
    private javax.swing.JLabel jRajinPiket;
    private javax.swing.JLabel jRajinRapat;
    private javax.swing.JList<String> jRapat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel jTahun;
    private javax.swing.JLabel jTeks;
    private javax.swing.JLabel jTeks1;
    private javax.swing.JLabel jTeks2;
    private javax.swing.JLabel jTeks5;
    private javax.swing.JTextField jtxt;
    // End of variables declaration//GEN-END:variables
}
